# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  database: empowerment
  pool: 5
  username: empowerment
  password: info-sys
  socket: /var/lib/mysql/mysql.sock
  host: localhost
  charset: utf8
  collation: utf8_general_ci

development:
  <<: *default
  database: empowerment

test:
  <<: *default
  database: empowerment_test

production:
  <<: *default
  database: empowerment
